service:
  http:
    h3: 
      enabled: false
      address:
        ip: ""
        port: 4431
    h1:
      enabled: true
      address:
        ip: ""
        port: 443
    h1_ssl:
      enabled: false
      address:
        ip: ""
        port: 4430
  tls:
    generate_if_missing: false
    certificate:
      raw: ""
      path: cert.pem
    key:
      raw: ""
      path: key.pem
  mcp:
    enabled: false
    address:
      ip: ""
      port: 4432
